// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PramosClearing.MarketService.Infrastructure.Persistence;

#nullable disable

namespace PramosClearing.Market.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20260306003646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("assets", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Code");

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Exchange", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.HasIndex("Country")
                        .HasDatabaseName("ix_exchanges_country");

                    b.ToTable("exchanges", (string)null);
                });

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Crypto", b =>
                {
                    b.HasBaseType("PramosClearing.MarketService.Domain.Entities.Asset");

                    b.Property<decimal?>("MaxSupply")
                        .HasPrecision(28, 8)
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("Network")
                        .HasDatabaseName("ix_cryptos_network");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_cryptos_symbol")
                        .HasFilter("[Symbol] IS NOT NULL");

                    b.ToTable("cryptos", (string)null);
                });

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Etf", b =>
                {
                    b.HasBaseType("PramosClearing.MarketService.Domain.Entities.Asset");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MarketIdentifier")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalExpenseRatio")
                        .HasPrecision(8, 6)
                        .HasColumnType("decimal(8,6)");

                    b.Property<string>("UnderlyingIndex")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("Exchange")
                        .HasDatabaseName("ix_etfs_exchange");

                    b.HasIndex("Symbol", "Exchange")
                        .IsUnique()
                        .HasDatabaseName("ix_etfs_symbol_exchange")
                        .HasFilter("[Symbol] IS NOT NULL AND [Exchange] IS NOT NULL");

                    b.ToTable("etfs", (string)null);
                });

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Stock", b =>
                {
                    b.HasBaseType("PramosClearing.MarketService.Domain.Entities.Asset");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MarketIdentifier")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("Exchange")
                        .HasDatabaseName("ix_stocks_exchange");

                    b.HasIndex("Symbol", "Exchange")
                        .IsUnique()
                        .HasDatabaseName("ix_stocks_symbol_exchange")
                        .HasFilter("[Symbol] IS NOT NULL AND [Exchange] IS NOT NULL");

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Crypto", b =>
                {
                    b.HasOne("PramosClearing.MarketService.Domain.Entities.Asset", null)
                        .WithOne()
                        .HasForeignKey("PramosClearing.MarketService.Domain.Entities.Crypto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Etf", b =>
                {
                    b.HasOne("PramosClearing.MarketService.Domain.Entities.Asset", null)
                        .WithOne()
                        .HasForeignKey("PramosClearing.MarketService.Domain.Entities.Etf", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PramosClearing.MarketService.Domain.Entities.Stock", b =>
                {
                    b.HasOne("PramosClearing.MarketService.Domain.Entities.Asset", null)
                        .WithOne()
                        .HasForeignKey("PramosClearing.MarketService.Domain.Entities.Stock", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
